services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=ionutqwerty
    ports:
      - "6379:6379"
    restart: unless-stopped
