services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--maxmemory", "64mb", "--maxmemory-policy", "allkeys-lru"]
    environment:
      - REDIS_PASSWORD=ionutqwerty
    ports:
      - "6379:6379"
    restart: unless-stopped
    mem_limit: 96m
    memswap_limit: 96m
