services:
  snmp-interogator:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: snmp_interogator
    network_mode: "host"
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=192.168.0.177
      - REDIS_PORT=6379
    restart: unless-stopped
