services:
  flask-api:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: sht21_rest_api_server
    network_mode: "host"
    ports:
      - "5500:5500"
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=192.168.50.1
      - REDIS_PORT=6379
    restart: unless-stopped
